#!/usr/bin/python3

import sys
from PIL import Image

#	Copyright (C) 2023 Victor Luchits
#
#	This file is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	This file is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <https://www.gnu.org/licenses/>.

def writebu16(f, v):
    f.write(v.to_bytes(2, "big", signed=False))

def patch2jagobj(fin, fout):
    im = Image.open(fin)
    data = im.tobytes()
    width = im.width
    height = im.height
    with open(fout, "wb") as fo:
        writebu16(fo, width)
        writebu16(fo, height)
        writebu16(fo, 3) # depth
        writebu16(fo, 0) # trans index
        writebu16(fo, 0) # pad
        writebu16(fo, 0) # pad
        writebu16(fo, 0) # pad
        writebu16(fo, 0) # pad
        fo.write(data)

patch2jagobj(sys.argv[1], sys.argv[2])

