#!/bin/env python3

#	Copyright (C) 2023 Victor Luchits
#
#	This file is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	This file is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <https://www.gnu.org/licenses/>.

import sys
import os
import mmap
import json
import hashlib
import concurrent.futures

from MultiCommand import MultiCommand
from BaseCommand import BaseCommand

dirname = ""
content = ""
s_startname = "S_START"
s_endname = "S_END"

def diskfn(fn):
    return os.path.join(dirname, fn)

def readu16(f):
    return int.from_bytes(f.read(2), "big", signed=False)

def readu32(f):
    return int.from_bytes(f.read(4), "big", signed=False)

def readu8(f):
    return int.from_bytes(f.read(1), "big", signed=False)

def eu8(v):
    return (v.to_bytes(1, "big", signed=False))

def ebu16(v):
    return (v.to_bytes(2, "big", signed=False))

def ebu32(v):
    return (v.to_bytes(4, "big", signed=False))

def writeu8(f, v):
    f.write(eu8(v))

def writebu16(f, v):
    f.write(ebu16(v))

def writebu32(f, v):
    f.write(ebu32(v))

def collen(col):
    topdelta = col[0]
    if topdelta == 255:
        return 1
    length = col[1]
    if length == 0:
        return 2
    return 4

def readpatchfile(f, newfmt=True, debug=False):
    width = readu16(f)
    height = readu16(f)
    offs = readu32(f)
    columnofs = []
    columns = []

    for i in range(width):
        columnofs.append(readu16(f))
    
    for i in range(width):
        f.seek(columnofs[i])
        while True:
            topdelta = readu8(f)
            if newfmt and topdelta == 255:
                columns.append((255, 255, 0))
                break
            length = readu8(f)
            stop = False
            if newfmt:
                stop = length & 0x80
                length = length & 0x7F
                length = length + 1
            if topdelta == 255 or length == 0:
                columns.append((255, 255, 0))
                break
            ofs = readu16(f)
            columns.append((topdelta, length, ofs))
            if stop:
                columns.append((255, 255, 0))
                break
    return (width, height, offs, columnofs, columns)

def readpatch(fin, newfmt=True, debug=False):
    with open(fin, "rb") as f:
        return readpatchfile(f, newfmt, debug)
    return (0, 0, 0, None, None)

def buildrawcolumns(width, columns):
    rawcolumns = []
    j = 0
    for i in range(width):
        raw = bytearray()
        while j < len(columns):
            col, j = columns[j], j + 1
            if col[0] == 255:
                raw.append(255)
                break
            if col[1] == 0:
                continue

            nextlast = False
            if j == len(columns):
                nextlast = True
            if not nextlast:
                nextcol = columns[j]
                if nextcol[0] == 255:
                    nextlast = True

            topdelta = col[0]
            length = col[1]-1
            offset = col[2]
            offset = ebu16(offset)

            if nextlast:
                raw.append(topdelta)
                raw.append(length|128)
                raw.extend(offset)
                j = j + 1
                break
            else:
                raw.append(topdelta)
                raw.append(length)
                raw.extend(offset)
        rawcolumns.append(raw)
    return rawcolumns

def writerawpatchfile(f, width, height, offs, columnofs, rawcolumns):
    writebu16(f, width)
    writebu16(f, height)
    writebu32(f, offs)

    for i in range(width):
        writebu16(f, columnofs[i])
    for c in rawcolumns:
        f.write(c)

def writepatchfile(f, width, height, offs, columnofs, columns):
    writerawpatchfile(f, width, height, offs, columnofs, buildrawcolumns(width, columns))

def writepatch(fin, width, height, offs, columnofs, columns, mode="wb"):
    with open(fin, mode) as f:
        writepatchfile(f, width, height, offs, columnofs, columns)

def writepixels(fin, pixels):
    with open(fin, "wb") as f:
        f.write(pixels)

def allsubcols(uniqcols):
    res = {}
    for c in uniqcols:
        res[c] = uniqcols[c]
    
    for pixels in uniqcols:
        col = uniqcols[pixels]
        pixels = list(pixels)
        collen = len(pixels)
        if collen == 1:
            continue
        for i in range(collen-1):
            subpixels = tuple(pixels[i+1:])
            if subpixels not in res:
                res[subpixels] = (col[0], collen-i-1, col[2]+i+1)

    return res

def optpatch(fin, fin2):
    origsize = os.path.getsize(fin)
    width, height, offs, columnofs, columns = readpatch(fin, False)

    uniqcols = {}
    with open(fin2, "rb") as f2:
        pixels = mmap.mmap(f2.fileno(), 0, access=mmap.ACCESS_COPY)
        
        j = 0
        for i in range(width):
            while j < len(columns):
                topdelta, length, dataofs = columns[j]
                if topdelta == 255:
                    j = j + 1
                    break

                data = tuple(pixels[dataofs:dataofs+length])

                x = uniqcols.get(data)
                if x:
                    if x[2] != dataofs:
                        #if length >= 1:
                        #    saved = saved + length
                        #print("duplicate %s %s %d -> %d" % (topdelta, length, dataofs, x[2]))
                        columns[j] = (columns[j][0], columns[j][1], x[2])
                else:
                    uniqcols[data] = (topdelta, length, dataofs)
                    if length > 1:
                        for i in range(length-1):
                            subpixels = tuple(pixels[dataofs+i+1:dataofs+length])
                            if subpixels not in uniqcols:
                                uniqcols[subpixels] = (topdelta, length-i-1, dataofs+i+1)
                j = j + 1

        pixels.close()

        rawcolums = buildrawcolumns(width, columns)
        newofs = 8 + width * 2
        for i in range(width):
            columnofs[i] = newofs
            newofs = newofs + len(rawcolums[i])

    writepatch(fin, width, height, offs, columnofs, columns)

    saved = origsize - os.path.getsize(fin)
    if saved > 0:
        print("%s\t%s" % (fin, saved))
    return saved

def optpixels(fin, fin2):
    size = os.path.getsize(fin2)
    width, height, offs, columnofs, columns = readpatch(fin)
    offsets = {}

    with open(fin2, "rb") as f2:
        pixels = mmap.mmap(f2.fileno(), 0, access=mmap.ACCESS_COPY)

        j = 0
        while j < len(columns):
            topdelta, length, dataofs = columns[j]
            if topdelta != 255:
                if dataofs in offsets:
                    l = offsets[dataofs]
                    if length > l:
                        offsets[dataofs] = length
                else:
                    offsets[dataofs] = length
            j = j + 1
        offsets = [(k,v) for k,v in offsets.items()]
        used = sorted(offsets, key=lambda x: x[0])

        #print(used)
        i = 0
        while i < len(used)-1:
            pos, length = used[i]
            nextpos, nextlength = used[i+1]
            if pos+length > nextpos:
                used = used[0:i] + used[i+1:]
                used[i] = (pos, nextpos+nextlength-pos)
                i = i - 1
            i = i + 1

        newpixels = bytearray()

        offset = 0
        k = 0
        origused = used.copy()
        while k < len(used):
            o, l = used[k]
            oo, ol = origused[k]
            if l > 0 and offset < o:
                j = 0
                while j < len(columns):
                    topdelta, length, dataofs = columns[j]
                    if topdelta != 255 and dataofs >= o:
                        #print("%s -> %s" % (dataofs, dataofs - (o - offset)))
                        columns[j] = (topdelta, length, dataofs - (o - offset))
                    j = j + 1
                j = k
                while j < len(used):
                    used[j] = (used[j][0] - (o - offset), used[j][1])
                    j = j + 1

            newpixels = newpixels + pixels[oo:oo+ol]
            offset = offset + l
            k = k + 1

        saved = 0

        pixels.close()
         
    rawcolums = buildrawcolumns(width, columns)
    newofs = 8 + width * 2
    for i in range(width):
        columnofs[i] = newofs
        newofs = newofs + len(rawcolums[i])

    writepatch(fin, width, height, offs, columnofs, columns)
    writepixels(fin2, newpixels)

    saved = size - os.path.getsize(fin2)
    if saved > 0:
        print("%s\t%s" % (fin2, saved))
    return saved

def findcontent(content, name):
    ind = 0
    for e in content:
        if "name" in e:
            if e["name"] == name:
                return (e, ind)
        ind = ind + 1
    return (None, -1)

def patchuniqs(fin, fin2):
    origsize = os.path.getsize(fin)
    width, _, _, _, columns = readpatch(fin)

    uniqcols = {}
    with open(fin2, "rb") as f2:
        pixels = mmap.mmap(f2.fileno(), 0, access=mmap.ACCESS_COPY)

        j = 0
        for i in range(width):
            while j < len(columns):
                topdelta, length, dataofs = columns[j]
                j = j + 1

                if topdelta == 255:
                    break

                data = tuple(pixels[dataofs:dataofs+length])
                x = uniqcols.get(data)
                if not x:
                    uniqcols[data] = (topdelta, length, dataofs)

        pixels.close()

    return uniqcols

def mergepatches(pixfn, uniqcols, fin, fin2):
    fullpix, partialpix = 0, 0
    origsize = os.path.getsize(pixfn)
    #print("%s %s" % (pixfn, origsize))
    width, height, offs, columnofs, columns = readpatch(fin)

    subcols = allsubcols(uniqcols)
    #subcols = uniqcols
    with open(pixfn, "ab") as f3:
        with open(fin2, "rb") as f2:
            pixels = mmap.mmap(f2.fileno(), 0, access=mmap.ACCESS_COPY)

            j = 0
            for i in range(width):
                while j < len(columns):
                    topdelta, length, dataofs = columns[j]

                    if topdelta == 255:
                        columns[j] = (topdelta, length, origsize)
                        j = j + 1
                        break

                    data = tuple(pixels[dataofs:dataofs+length])
                    x = subcols.get(data)
                    if not x:
                        uniqcols[data] = (topdelta, length, origsize)
                        subcols[data] = (topdelta, length, origsize)
                        data = bytearray(data)
                        f3.write(data)
                        columns[j] = (topdelta, length, origsize)
                        origsize += len(data)
                    else:
                        if uniqcols.get(data):
                            fullpix += length
                        else:
                            partialpix += length
                        columns[j] = (topdelta, length, x[2])

                    j = j + 1

            pixels.close()

        rawcolums = buildrawcolumns(width, columns)
        newofs = 8 + width * 2
        for i in range(width):
           columnofs[i] = newofs
           newofs = newofs + len(rawcolums[i])
    writepatch(fin, width, height, offs, columnofs, columns)

    return (uniqcols, fullpix, partialpix)

def comparepatches(cols, cols2):
    pix = 0
    for col in cols2:
        if col in cols:
            pix += len(col)
    return pix

def crunchpatches(uniqs = {}, minthreshold=0, maxthreshold=0, skipsize=False, max_workers=None):
    global s_endname
    global s_startname

    totalpix = 0
    totalcnt = 0

    _, s_start = findcontent(content, s_startname)
    _, s_end = findcontent(content, s_endname)

    sha1uniqs = {}
    sha1s = [''] * len(content)

    # --- Multi-threaded SHA1 Hash Pre-pass ---
    hash_tasks = []
    i = s_start
    if "filename" not in content[i]:
        i = i + 1
    while i < s_end:
        fn = content[i]["filename"]
        patch = diskfn(fn)
        pixels = diskfn(content[i+1]["filename"])
        hash_tasks.append((i, fn, patch, pixels))
        i = i + 2

    def _hash_worker(item):
        idx, fn, patch, pixels = item
        results = []
        for j, tfn in enumerate([patch, pixels]):
            sha1 = hashlib.sha1()
            with open(tfn, "rb") as f:
                sha1.update(f.read())
            results.append((idx + j, sha1.hexdigest()))
        
        # Calculate patchuniqs on the worker thread as well
        cols = patchuniqs(patch, pixels)
        return fn, patch, pixels, results, cols

    with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
        for fn, patch, pixels, hash_results, cols in executor.map(_hash_worker, hash_tasks):
            for idx, digest in hash_results:
                sha1uniqs[digest] = sha1uniqs.get(digest, 0) + 1
                sha1s[idx] = digest

            if fn not in uniqs:
                uniqs[fn] = (False, cols, [])
    # --- End SHA1 Multi-threaded Pre-pass ---

    i = s_start
    if "filename" not in content[i]:
        i = i + 1

    while i < s_end:
        fn = content[i]["filename"]
        pixfn = diskfn(content[i+1]["filename"])
        pixfnsize = os.path.getsize(pixfn)

        mapped, cols, pixfns = uniqs[fn]
        if mapped:
            i = i + 2
            continue

        bestpix = minthreshold - 1
        bestmatch = -1
        bestcols = None

        # --- Multi-threaded Inner Candidate Evaluation ---
        candidates = []
        j = i + 2
        while j < s_end:
            fn2 = content[j]["filename"]
            pixfn2 = diskfn(content[j+1]["filename"])
            pixfnsize2 = os.path.getsize(pixfn2)

            # guard against ridiculously big lumps
            if pixfnsize + pixfnsize2 > 62 * 1024:
                j = j + 2
                continue

            if fn2 == fn:
                j = j + 2
                continue
            mapped, cols2, pixfns2 = uniqs[fn2]
            if mapped or len(pixfns2) > 0:
                j = j + 2
                continue

            # Store payload for thread worker
            candidates.append((j, fn2, cols2))
            j = j + 2

        if candidates:
            def _eval_candidate(item):
                cand_j, cand_fn2, cand_cols2 = item
                pix_val = comparepatches(cols, cand_cols2)
                return cand_j, cand_fn2, cand_cols2, pix_val

            with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
                results = executor.map(_eval_candidate, candidates)
                
                for cand_j, cand_fn2, cand_cols2, pix in results:
                    if pix > bestpix:
                        if skipsize or sha1uniqs[sha1s[cand_j]] == 1 or pix > os.path.getsize(diskfn(cand_fn2)):
                            bestpix = pix
                            bestmatch = cand_j
                            bestcols = cand_cols2
        # --- End Inner Loop ---

        if bestpix >= minthreshold and (maxthreshold == 0 or bestpix < maxthreshold):
            totalcnt = totalcnt + 1
            fn2 = content[bestmatch]["filename"]
            pixfn2 = diskfn(content[bestmatch+1]["filename"])

            cols, fullpix, partialpix = mergepatches(pixfn, cols, diskfn(fn2), pixfn2)
            print("merged %s into %s: %s/%s pixels in full/partial columns" % (fn, fn2, fullpix, partialpix))

            totalpix = totalpix + fullpix + partialpix

            pixfns.append(pixfn2)
            pixfns = pixfns + uniqs[fn2][2]

            uniqs[fn2] = (True, bestcols, [])
            uniqs[fn] = (False, cols, pixfns)

            # copy pixels
            with open(pixfn, "rb") as fin:
                pixels = fin.read()
                for pixfn2 in pixfns:
                    with open(pixfn2, "wb") as fout:
                        fout.write(pixels)

        i = i + 2

    print("total\t\t%s" % totalpix)
    return uniqs, totalcnt

def optimizepatches():
    global s_endname
    global s_startname

    totalpix = 0
    _, s_start = findcontent(content, s_startname)
    _, s_end = findcontent(content, s_endname)

    i = s_start
    if "filename" not in content[i]:
        i = i + 1
    while i < s_end:
        fn = content[i]["filename"]
        patch = diskfn(fn)
        pixels = diskfn(content[i+1]["filename"])

        print("optimizing %s" % fn)

        totalpix += optpatch(patch, pixels)
        totalpix += optpixels(patch, pixels)

        i = i + 2
    print("total\t%s" % totalpix)

def squishpatches(uniqs = {}):
    global s_endname
    global s_startname

    totalsaved = 0

    _, s_start = findcontent(content, s_startname)
    _, s_end = findcontent(content, s_endname)

    sha1uniqs = {}
    nameuniqs = {}
    sha1s = [''] * len(content)

    i = s_start
    if "filename" not in content[i]:
        i = i + 1
    while i < s_end:
        fn = content[i]["filename"]
        pixels = diskfn(content[i+1]["filename"])

        for tfn in [pixels]:
            sha1 = hashlib.sha1()
            data = b""
            with open(tfn, "rb") as f:
                data = f.read()
            sha1 = hashlib.sha1()
            sha1.update(data)
            sha1 = sha1.hexdigest()

            name = content[i]["name"][:4]
            if name not in nameuniqs:
                nameuniqs[name] = sha1

            if sha1 not in sha1uniqs:
                sha1uniqs[sha1] = [i]
            else:
                sha1uniqs[sha1].append(i)
            sha1s[i] = sha1

        i = i + 2

    for k in sha1uniqs:
        patches = sha1uniqs[k]
        if len(patches) >= 2:
            continue

        patch = patches[0]
        name = content[patch]["name"][:4]
        sha1 = nameuniqs[name]
        sha1uniqs[sha1].append(patch)

    for k in sha1uniqs:
        patches = sha1uniqs[k]
        if len(patches) < 2:
            continue

        batch = list()
        coluniqs = {}

        n = len(patches) - 1
        while n >= 0:
            patch = patches[n]
            fn = content[patch]["filename"]
            width, height, offs, columnofs, columns = readpatch(diskfn(fn))
            ofs = 8 + width * 2
            patchlen = ofs

            rawcolumns = buildrawcolumns(width, columns)

            for i in range(width):
                raw = rawcolumns[i]
                data = tuple(raw)
                if data not in coluniqs:
                    uniqparts = []

                    m = collen(raw)
                    while m < len(raw):
                        data = tuple(raw[m:])
                        if data not in coluniqs:
                            uniqparts.append(data)
                            coluniqs[data] = (n, patchlen+m, [])
                        m = m + collen(raw[m:])

                    data = tuple(raw)
                    coluniqs[data] = (n, patchlen, uniqparts)
                    patchlen = patchlen + len(raw)
                ofs = ofs + len(raw)

            batch.append((width, height, offs, columnofs, rawcolumns, patch, ofs, patchlen, 0))

            n = n - 1
            totalsaved = totalsaved + (ofs - patchlen)

        # reverse order
        patches = []
        bloblen = 0
        for n in range(len(batch)):
            patch = list(batch.pop())
            patch[8] = bloblen
            patchlen = patch[7]
            if patchlen & 1:
                patchlen = patchlen + 1
            bloblen = bloblen + patchlen
            patches.append(tuple(patch))

        # distances from each patch to other patches
        dists = [0]*len(patches)
        for n in range(len(patches)):
            pos = patches[n][8]
            dists[n] = [0]*len(patches)
            for j in range(len(patches)):
                dists[n][j] = patches[j][8] - pos

        for n, patch in enumerate(patches):
            fn = content[patch[5]]["filename"]
            fin = diskfn(fn)

            with open(fin, "wb") as f:
                m = n
                while m < len(patches):
                    written = {}
                    patch = patches[m]
                    width, height, offs, columnofs, rawcolumns, _, _, patchlen, _ = patch

                    flen = f.tell()

                    for i in range(width):
                        data = tuple(rawcolumns[i])
                        u = coluniqs[data]
                        colofs = dists[m][u[0]]
                        if colofs & 1:
                            colofs = colofs + 1
                        colofs = colofs + u[1]
                        columnofs[i] = colofs

                    newrawcolumns = []
                    for i in range(width):
                        data = tuple(rawcolumns[i])
                        u = coluniqs[data]

                        if u[0] == m and data not in written:
                            newrawcolumns.append(rawcolumns[i])
                            written[data] = True
                            for part in u[2]:
                                written[part] = True

                    writerawpatchfile(f, width, height, offs, columnofs, newrawcolumns)

                    flen = f.tell() - flen
                    if flen != patchlen:
                        print(fin)
                        print(flen, patchlen)
                        sys.exit(1)
                    if patchlen & 1:
                        writeu8(f, 255)
                    m = m + 1

    print("total\t\t%s" % totalsaved)

def merge_pixel_runs_scs(runs):
    """
    Optimized Greedy Shortest Common Superstring (SCS) implementation.
    Maximizes suffix-to-prefix overlap while correctly maintaining exact offsets.
    """
    if not runs:
        return bytearray(), {}

    # Deduplicate while preserving original run identities
    unique_runs = tuple(set(runs))
    num_runs = len(unique_runs)
    
    if num_runs == 1:
        return bytearray(unique_runs[0]), {unique_runs[0]: 0}

    # Pre-convert sequences to bytes for fast execution and slice matching
    nodes = [bytes(r) for r in unique_runs]

    # Pre-calculate all non-zero suffix-to-prefix overlaps O(N^2 * L)
    # Stores (overlap_len, src_index, dst_index)
    overlaps = []
    for i in range(num_runs):
        node_i = nodes[i]
        len_i = len(node_i)
        for j in range(num_runs):
            if i == j:
                continue
            node_j = nodes[j]
            max_len = min(len_i, len(node_j))
            # Check overlaps from longest to shortest
            for length in range(max_len, 0, -1):
                if node_i[-length:] == node_j[:length]:
                    overlaps.append((length, i, j))
                    break

    # Sort overlaps descending by length
    overlaps.sort(key=lambda x: x[0], reverse=True)

    # Disjoint-set / Path-linking tracking to prevent cycles
    parent = list(range(num_runs))
    next_node = [-1] * num_runs
    prev_node = [-1] * num_runs

    def find_root(i):
        path = []
        while parent[i] != i:
            path.append(i)
            i = parent[i]
        for node in path:
            parent[node] = i
        return i

    # Greedy merging phase: O(N^2)
    for ov, i, j in overlaps:
        if next_node[i] != -1 or prev_node[j] != -1:
            continue
        
        root_i = find_root(i)
        root_j = find_root(j)
        
        # Avoid forming loops
        if root_i != root_j:
            next_node[i] = (j, ov)
            prev_node[j] = i
            parent[root_j] = root_i

    # Assemble concatenated path chains and compute exact offsets
    merged_bytes = bytearray()
    offsets = {}
    visited = [False] * num_runs

    for i in range(num_runs):
        if prev_node[i] == -1 and not visited[i]:
            curr = i
            chain_start_offset = len(merged_bytes)
            
            while curr != -1:
                visited[curr] = True
                curr_node = nodes[curr]
                
                # Assign exact starting position in the merged bytearray
                offsets[unique_runs[curr]] = len(merged_bytes)
                
                if next_node[curr] != -1:
                    nxt, ov = next_node[curr]
                    merged_bytes.extend(curr_node[:-ov])
                    curr = nxt
                else:
                    merged_bytes.extend(curr_node)
                    curr = -1

    return merged_bytes, offsets


def optpixels_scs(fin, fin2):
    """
    SCS-optimized optpixels that restructures the pixel binary using graph-based
    suffix-to-prefix merging while updating column offsets.
    """
    size = os.path.getsize(fin2)
    width, height, offs, columnofs, columns = readpatch(fin)

    runs_in_use = []
    col_run_map = []  # Maps each non-255 column post index to its pixel tuple

    with open(fin2, "rb") as f2:
        pixels = mmap.mmap(f2.fileno(), 0, access=mmap.ACCESS_COPY)

        j = 0
        while j < len(columns):
            topdelta, length, dataofs = columns[j]
            if topdelta != 255:
                run = tuple(pixels[dataofs:dataofs + length])
                runs_in_use.append(run)
                col_run_map.append((j, topdelta, length, run))
            j += 1

        pixels.close()

    # Generate the merged pixel buffer using SCS overlap
    newpixels, run_offsets = merge_pixel_runs_scs(runs_in_use)

    # Update columns with their new offset in the merged pixel buffer
    for col_idx, topdelta, length, run in col_run_map:
        new_dataofs = run_offsets[run]
        columns[col_idx] = (topdelta, length, new_dataofs)

    # Rebuild patch headers and output files
    rawcolumns = buildrawcolumns(width, columns)
    newofs = 8 + width * 2
    for i in range(width):
        columnofs[i] = newofs
        newofs = newofs + len(rawcolumns[i])

    writepatch(fin, width, height, offs, columnofs, columns)
    writepixels(fin2, newpixels)

    saved = size - os.path.getsize(fin2)
    if saved > 0:
        print("%s\t%s" % (fin2, saved))
    return saved

def _process_single_patch_scs(item):
    """
    Helper worker function to process a single patch/pixel pair.
    Returns (filename, saved_bytes).
    """
    fn, patch, pixels = item
    print("SCS-optimizing pixels for %s" % fn)
    saved = optpixels_scs(patch, pixels)
    return fn, saved

def optpixelsscs_all(max_workers=None):
    """
    Multi-threaded version of optpixelsscs_all.
    max_workers defaults to CPU core count if set to None.
    """
    global s_endname
    global s_startname

    _, s_start = findcontent(content, s_startname)
    _, s_end = findcontent(content, s_endname)

    # Collect all tasks (file pairs) first
    tasks = []
    i = s_start
    if "filename" not in content[i]:
        i = i + 1
    while i < s_end:
        fn = content[i]["filename"]
        patch = diskfn(fn)
        pixels = diskfn(content[i+1]["filename"])
        tasks.append((fn, patch, pixels))
        i = i + 2

    totalpix = 0

    # Process patch files in parallel using a ThreadPoolExecutor
    with concurrent.futures.ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = [executor.submit(_process_single_patch_scs, task) for task in tasks]
        
        for future in concurrent.futures.as_completed(futures):
            try:
                fn, saved = future.result()
                totalpix += saved
            except Exception as exc:
                print("Error processing patch: %s" % exc)

    print("total saved\t%s" % totalpix)

class CommandPatchOpt(BaseCommand):
    def __init__(self, cmd, args):
        global dirname
        global content
        global s_endname
        global s_startname

        BaseCommand.__init__(self, cmd, args)

        dirname = args.dir
        with open(os.path.join(dirname, "content.json")) as f:
            content = json.load(f)
        dirname = os.path.join(dirname, "files")
        s_endname = args.s_end
        s_startname = args.s_start

class CommandOptimize(CommandPatchOpt):
    def __init__(self, cmd, args):
        CommandPatchOpt.__init__(self, cmd, args)

        print("Optimizing patches...")

        optimizepatches()

class CommandCrunch(CommandPatchOpt):
    def __init__(self, cmd, args):
        CommandPatchOpt.__init__(self, cmd, args)

        threads = getattr(args, "threads", None)
        print("Crunching patches...")

        uniqs = {}
        minthreshold = 8000
        while True:
            uniqs, cnt = crunchpatches(uniqs, minthreshold=minthreshold, max_workers=threads)
            if minthreshold == 16:
                break
            if cnt != 0:
                continue
            minthreshold = int(minthreshold * 0.75)
            if minthreshold < 16:
                minthreshold = 16

class CommandSquish(CommandPatchOpt):
    def __init__(self, cmd, args):
        CommandPatchOpt.__init__(self, cmd, args)

        print("Squishing patches...")

        squishpatches()

class CommandOptPixelsSCS(CommandPatchOpt):
    def __init__(self, cmd, args):
        CommandPatchOpt.__init__(self, cmd, args)

        threads = getattr(args, "threads", None)
        print("Optimizing pixel buffers via SCS (Threads: %s)..." % (threads or "Auto"))

        optpixelsscs_all(max_workers=threads)
    
mc = MultiCommand()

def genparser(parser):
    parser.add_argument("--s_start", default = "S_START", type = str, help = "S_START lump name.")
    parser.add_argument("--s_end", default = "S_END", type = str, help = "S_END lump name.")
    parser.add_argument("--dir", metavar = "directory", type = str, help = "Input directory that should be compiled to a WAD.")
mc.register("optimize", "Remove redundant data from individual sprite patches", genparser, action = CommandOptimize)

def genparser(parser):
    parser.add_argument("--s_start", default = "S_START", type = str, help = "S_START lump name.")
    parser.add_argument("--s_end", default = "S_END", type = str, help = "S_END lump name.")
    parser.add_argument("--dir", metavar = "directory", type = str, help = "Input directory that should be compiled to a WAD.")
    parser.add_argument("--threads", default=None, type=int, help="Number of parallel threads to use (default: CPU count).")
mc.register("crunch", "Crunch patches, removing redundant data across multiple files", genparser, action = CommandCrunch)

def genparser(parser):
    parser.add_argument("--s_start", default = "S_START", type = str, help = "S_START lump name.")
    parser.add_argument("--s_end", default = "S_END", type = str, help = "S_END lump name.")
    parser.add_argument("--dir", metavar = "directory", type = str, help = "Input directory that should be compiled to a WAD.")
mc.register("squish", "Crunch patches, removing redundant data across multiple files", genparser, action = CommandSquish)

def genparser(parser):
    parser.add_argument("--s_start", default="S_START", type=str, help="S_START lump name.")
    parser.add_argument("--s_end", default="S_END", type=str, help="S_END lump name.")
    parser.add_argument("--dir", metavar="directory", type=str, help="Input directory that should be compiled to a WAD.")
    parser.add_argument("--threads", default=None, type=int, help="Number of parallel threads to use (default: CPU count).")
mc.register("optpixels-scs", "Optimize pixel buffers using Shortest Common Superstring overlap", genparser, action=CommandOptPixelsSCS)

mc.run(sys.argv[1:])
