#!/usr/bin/python3

#	Copyright (C) 2023 Victor Luchits
#
#	This file is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	This file is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <https://www.gnu.org/licenses/>.

import sys

def writebu32(f, v):
    f.write(v.to_bytes(4, "big", signed=False))

def raw2jagsnd(fin, fout):
    with open(fin, "rb") as f:
        samples = f.read()

        with open(fout, "wb") as o:
            writebu32(o, len(samples)) # samples
            writebu32(o, 0) # loop start
            writebu32(o, len(samples)) # loop end
            writebu32(o, 1) # info
            writebu32(o, 0) # unity
            writebu32(o, 128) # pitch_correction
            writebu32(o, 0) # decay_step
            o.write(samples)

raw2jagsnd(sys.argv[1], sys.argv[2])
