#!/usr/bin/python3
#	wadcode - WAD compiler/decompiler for WAD resource files
#	Copyright (C) 2019-2019 Johannes Bauer
#
#	This file is part of wadcode.
#
#	wadcode is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	wadcode is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
#	Johannes Bauer <JohannesBauer@gmx.de>

import sys
from CommandCombine import CommandCombine
from MultiCommand import MultiCommand

mc = MultiCommand()

def genparser(parser):
	parser.add_argument("wad32x", metavar = "wadfile", type = str, help = "")
	parser.add_argument("wadjag", metavar = "wadfile", type = str, help = "")
	parser.add_argument("wadout", metavar = "wadfile", type = str, help = "")
mc.register("combine", "Compile a WAD file from resources", genparser, action = CommandCombine)

mc.run(sys.argv[1:])
